version: '3'
services:
  nodered:
    depends_on:
        - grafana
    image: nodered/node-red:latest
    ports:
        - "1880:1880"
    volumes:
        - nodered-storage:/data
  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=myorg
      - DOCKER_INFLUXDB_INIT_BUCKET=mybucket
    volumes:
      - influxdb-storage:/var/lib/influxdb
      
  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - grafana-provisioning:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123

  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./configs/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./configs/password.txt:/mosquitto/password.txt
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log


volumes:
  nodered-storage:
  grafana-provisioning:
  grafana-storage:
  influxdb-storage:
  mosquitto-data:
  mosquitto-log:
  